# Generated by Django 4.1.3 on 2022-12-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
