# Generated by Django 4.1.3 on 2022-12-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
